# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dt_norm <- function(x, location, scale, L, U, do_log) {
    .Call(`_espresso_dt_norm`, x, location, scale, L, U, do_log)
}

rt_norm <- function(n, location, scale, L, U) {
    .Call(`_espresso_rt_norm`, n, location, scale, L, U)
}

d_Binom <- function(x, size, prob, do_log) {
    .Call(`_espresso_d_Binom`, x, size, prob, do_log)
}

